### PR TITLE
Fix typo in base-template.yaml

### PR DESCRIPTION
**Pull request by revit13**
This PR contains a minor typo fix to base-template.yaml

### CODE REVIEW

**Comment by accorvin** [comment]
@revit13 thank you for the PR!

@Maxusmusti @dimakis can you all take a look?

**Review by dimakis — APPROVED** [review]
LGTM

**Review by Maxusmusti — CHANGES_REQUESTED** [review]
Looks good, but could you update the tests as well? (Guessing it will just be updating the yamls in the test dir with the same `replica`->`replicas`)

**Comment by revit13** [comment]
> Looks good, but could you update the tests as well? (Guessing it will just be updating the yamls in the test dir with the same `replica`->`replicas`)

@Maxusmusti Done, Thanks

**Review by MichaelClifford — APPROVED** [review]

**Pull request merged**
