### PR TITLE
ci: fix coverage badge wf and omit test files from unit test coverage

### PR DESCRIPTION
**Pull request by Bobbins228**
# Issue link

# What changes have been made

# Verification steps

Run `coverage run --omit="src/**/test_*.py,src/codeflare_sdk/common/utils/unit_test_support.py" -m pytest` and verify the unit test files are not included when you run `coverage report`
## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] Testing is not required for this change

### CODE REVIEW

**Review by Ygnas — APPROVED** [review]

**Review by Ygnas — APPROVED** [review]
Verified works as expected.

**Review by varshaprasad96 — APPROVED** [review]
/lgtm
/approve

**Comment by akram** [comment]
thanks @Bobbins228 , this is somehting I have noticed while trying to push my PR; and it was biasing the coverage results.
Having now the rule global will make things better.
Also, we could have a `.coveragerc` file that has this to make tests also run the same way locally.

**Comment by Bobbins228** [comment]
A .coveragerc file could be good! Would help rather than having to make sure 2 workflows and documentation are kept updated. I will look into this thanks Akram :+1:

**Comment by akram** [comment]
here is the `.coveragerc`  that I use:
```
[run]
omit =
    src/**/test_*.py,src/codeflare_sdk/common/utils/unit_test_support.py

[report]
exclude_lines =
    pragma: no cover
 ```
 
 and since I put it, unit tests appears in vscode now

image

**Pull request merged**
