### PR TITLE
Remove automatic triage/needs-triage label creation

### PR DESCRIPTION
**Pull request by sutaakar**
# Issue link

# What changes have been made

Remove workflow job adding triage/needs-triage label for new issues. Currently the triage is leveraging priority field.

# Verification steps

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] Testing is not required for this change

### CODE REVIEW

**Review by Bobbins228 — COMMENTED** [review]
/lgtm

**Review by ChristianZaccaria — COMMENTED** [review]
This PR is highly related to this one: https://github.com/opendatahub-io/distributed-workloads/pull/148 
and: https://github.com/project-codeflare/codeflare-common/pull/8 

There were thoughts of updating this workflow and moving it to the codeflare-common repo for all components to use (depending on how much work is involved, so not entirely necessary).

Should we instead then just remove that job from each repo? Which includes ODH/CFO, project-codeflare/CFO, MCAD, InstaScale, CodeFlare SDK? <-- I think I vote for this.

**Comment by sutaakar** [comment]
> Should we instead then just remove that job from each repo?

Are you referring to the `Add issue to project` job? I think that this job still has sense, the question is how to apply it for all repositories without unnecessary duplications.

**Review by ChristianZaccaria — CHANGES_REQUESTED** [review]
Adding same comment on this PR for adjusting the first line of this file :+1:

**Comment by sutaakar** [comment]
@ChristianZaccaria thanks, done

**Review by Bobbins228 — APPROVED** [review]
/approve

**Pull request merged**
