### PR TITLE
add: simplified import statements for the codeflare-sdk

### PR DESCRIPTION
**Pull request by VanillaSpoon**
# Issue link
closes https://issues.redhat.com/browse/RHOAIENG-2109

# What changes have been made
This pr introduces a simplified import approach for the codeflare-sdk. Reducing the nested element of import statements. 
For example: 
```py
    from codeflare_sdk.cluster.cluster import Cluster, ClusterConfiguration
    from codeflare_sdk.cluster.auth import TokenAuthentication
```

Becomes: 
```py
    from codeflare_sdk import Cluster, ClusterConfiguration, TokenAuthentication
```

This pr also contains the relevent updates to documentation and example notebooks.

# Verification steps
Build the sdk and install it on your notebook.
Run through the examples, with the updated import statements, and ensure everything runs.

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] Testing is not required for this change

### CODE REVIEW

**Review by Bobbins228 — COMMENTED** [review]
Awesome work Eoin a well needed change.
Tested out the imports and we are all green I just have one concern.

Iirc we normally don't update the demo notebooks with changes from main until after a release @KPostOffice keep me honest? :)

**Comment by VanillaSpoon** [comment]
> Awesome work Eoin a well needed change. Tested out the imports and we are all green I just have one concern.
> 
> Iirc we normally don't update the demo notebooks with changes from main until after a release @KPostOffice keep me honest? :)

Oh yea, thinking now that would be right :) thanks @Bobbins228

**Review by Bobbins228 — COMMENTED** [review]
/lgtm

**Comment by ChristianZaccaria** [comment]
Great job! /lgtm . I suggest to create a Jira to keep track of the follow-on issue to update notebooks, tests (e2e and others), etc.

**Review by ChristianZaccaria — APPROVED** [review]
Great job! /lgtm . I suggest to create a Jira to keep track of the follow-on issue to update notebooks, tests (e2e and others), etc.

**Review by Bobbins228 — APPROVED** [review]
/approve

**Pull request merged**
