### PR TITLE
Enhance ray module code documentation

### PR DESCRIPTION
**Pull request by Ygnas**
# Issue link

[https://issues.redhat.com/browse/RHOAIENG-13959](https://issues.redhat.com/browse/RHOAIENG-13959)
# What changes have been made

Enhanced ray module code documentation
# Verification steps

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [x] Testing is not required for this change

### CODE REVIEW

**Review by KPostOffice — COMMENTED** [review]
Just a small comment

**Review by KPostOffice — COMMENTED** [review]
/lgtm

**Review by Bobbins228 — APPROVED** [review]
/lgtm /approve

**Pull request merged**
