### PR TITLE
remove: DDPJobDefinition from SDK

### PR DESCRIPTION
**Pull request by VanillaSpoon**
# Issue link
https://issues.redhat.com/browse/RHOAIENG-5096

# What changes have been made
This pr contains a removal of the  DDPJobDefinition from the codeflare-sdk, as well as updated tests to reflect the change. 

A follow up pr will be made to update the docs and demo notebooks upon being merged.

# Verification steps
Run the sdk tests and ensure they are functioning correctly. 
Run a demo notebook to ensure no breaks.

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] Testing is not required for this change

### CODE REVIEW

**Review by Bobbins228 — COMMENTED** [review]
/lgtm

**Comment by Srihari1192** [comment]
@VanillaSpoon  Tried running tests `mnist_raycluster_sdk_oauth_test.py`  and demo notebooks with cluster configuration defined , App wrapper creation is fine but Ray Cluster creation is Failing.. 

Tried running on installing Main branch aswell , same error 
@ChristianZaccaria Does we missed any cluster configuration here?

`tests/e2e/mnist_raycluster_sdk_oauth_test.py::TestRayClusterSDKOauth::test_mnist_ray_cluster_sdk_auth Insecure request warnings have been disabled
Written to: /opt/app-root/src/.codeflare/appwrapper/mnist.yaml
AppWrapper 'mnist' has been created in the namespace: 'test-ns-8iw5r'
╭──────────────────────╮
│   🚀 Cluster Queue   │
│      Status 🚀       │
│ +-------+----------+ │
│ | Name  | Status   | │
│ +=======+==========+ │
│ | mnist | queueing | │
│ |       |          | │
│ +-------+----------+ │
╰──────────────────────╯
Waiting for requested resources to be set up...`



`cluster = Cluster(ClusterConfiguration(
    name='jobtest',
    namespace='test-dw',
    num_workers=2,
    head_cpus="500m",
    head_memory=2,
    min_cpus=1,
    max_cpus=1,
    min_memory=4,
    max_memory=4,
    num_gpus=0,
    image="quay.io/project-codeflare/ray:latest-py39-cu118",
    instascale=False,
    write_to_file=True,
))`

**Comment by ChristianZaccaria** [comment]
@Srihari1192 Those clusterconfiguration look good to me, the openshift_oauth is removed as we are defaulting to it to be true. And all oauth resources are created by the RC Controller in Main

**Comment by KPostOffice** [comment]
You can remove `torchx_config` function in `cluster.py` and `torchx_scheduler = "ray"` as well as imports involving torchx at the top of `unit_test.py` and remove `torchx` from requirements.

**Pull request merged**
