### PR TITLE
Simplify yaml generation by starting from non-AppWrapper template

### PR DESCRIPTION
**Pull request by dgrove-oss**
The v1/beta2 AppWrapper can be wrapped around a RayCluster as a simple prefix to the "real" yaml.  So we can simplify yaml generation/manipulation by starting with a vanilla RayCluster and just optionally put it inside an AppWrapper at the end.

### CODE REVIEW

**Review by KPostOffice — COMMENTED** [review]
This /lgtm, can you rebase?

**Comment by dgrove-oss** [comment]
rebased

**Review by VanillaSpoon — COMMENTED** [review]
/lgtm

Needs another rebase and we can get this in :)

**Comment by dgrove-oss** [comment]
rebased

**Review by Bobbins228 — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
