### PR TITLE
SA get current namespace

### PR DESCRIPTION
**Pull request by KPostOffice**
# Issue link
supersedes #539 

# What changes have been made
add check for SA namespace as default

# Verification steps
use RHOAI workbook, clone this branch and `run pip install .` see that the namespace retrieved is the same as the project that you are in

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] Testing is not required for this change

### CODE REVIEW

**Review by ChristianZaccaria — COMMENTED** [review]
Will we want to enable the following test as part of this fix, or address in a separate PR?
https://github.com/project-codeflare/codeflare-sdk/blob/main/src/codeflare_sdk/cluster/cluster.py#L724 

Apart from the above question, all works as expected!
https://github.com/project-codeflare/codeflare-sdk/blob/main/tests/unit_test.py#L579

**Comment by ChristianZaccaria** [comment]
Wondering if it's a good idea to set something like this to all notebooks, further removing the need for user input:
```
cluster = Cluster(ClusterConfiguration(
    name='raytest',
    namespace= cluster.get_current_namespace(),
```
I think we would need to add the import too for usage:
`from codeflare_sdk.cluster import cluster`

**Comment by KPostOffice** [comment]
> Wondering if it's a good idea to set something like this to all notebooks, further removing the need for user input:
> 
> ```
> cluster = Cluster(ClusterConfiguration(
>     name='raytest',
>     namespace= cluster.get_current_namespace(),
> ```
> 
> I think we would need to add the import too for usage: `from codeflare_sdk.cluster import cluster`

If config doesn't have a namespace set [it should use the current working namespace](https://github.com/project-codeflare/codeflare-sdk/blob/b4c55e4910222e2be8a7f8c7026b98287c9a9cbe/src/codeflare_sdk/cluster/cluster.py#L143)

**Comment by KPostOffice** [comment]
> Will we want to enable the following test as part of this fix, or address in a separate PR? https://github.com/project-codeflare/codeflare-sdk/blob/main/src/codeflare_sdk/cluster/cluster.py#L724
> 
> https://github.com/project-codeflare/codeflare-sdk/blob/main/tests/unit_test.py#L579
> 
> Apart from the above question, all works as expected!

I'm not sure what the test is testing exactly. Can we leave it out for now?

**Comment by Fiona-Waters** [comment]
I ran a demo notebook without providing the namespace and the `rhods-notebooks` namespace was retrieved from `/var/run/secrets/kubernetes.io/serviceaccount/namespace`. Works as expected.
/approve

**Pull request merged**
