### PR TITLE
Login method error return

### PR DESCRIPTION
**Pull request by oksanabaza**
# Issue link
https://issues.redhat.com/browse/RHOAIENG-531

# What changes have been made
Login method returns the error to the caller

# Verification steps

## Checks
- [x] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] Testing is not required for this change

### CODE REVIEW

**Review by Bobbins228 — COMMENTED** [review]
/lgtm

**Comment by ChristianZaccaria** [comment]
I had to manually activate and run the GitHub Actions workflows. It seems @oksanabaza is not part of the Maintainers list so can't run them on PRs made. Perhaps she should be added? @Bobbins228

**Review by ChristianZaccaria — APPROVED** [review]
/lgtm

**Review by Bobbins228 — APPROVED** [review]
/approve

**Pull request merged**
