### PR TITLE
install py-3.11 for sync

### PR DESCRIPTION
**Pull request by KPostOffice**
# Issue link
https://issues.redhat.com/browse/RHOAIENG-11541

# What changes have been made
Added another version of python to be installed as part of GH action in accordance with [this documentation](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#specifying-multiple-pythonpypy-versions)

# Verification steps

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] Testing is not required for this change

### CODE REVIEW

**Comment by KPostOffice** [comment]
https://github.com/KPostOffice/notebooks/pull/1/files

See example PR from this workflow (successfully updates 3.11 Pipfiles

**Review by Bobbins228 — COMMENTED** [review]
/lgtm

**Comment by KPostOffice** [comment]
Accidentally opened this PR upstream with the changes to the workflow file but it's here

https://github.com/opendatahub-io/notebooks/pull/698

**Comment by KPostOffice** [comment]
@Bobbins228 PTAL

**Review by Bobbins228 — COMMENTED** [review]
/lgtm 
nice work on shaving down the "Extracting only directories from file paths" step!

**Review by varshaprasad96 — APPROVED** [review]
+1! Like `grep` over the script!

/lgtm
/approve

**Pull request merged**
