### PR TITLE
[205] Fix codeflare-sdk release action

### LINKED ISSUE #205: Fix codeflare-sdk release action
The codeflare-sdk generates and commits docs that are breaking the precommit. We should fix this.

### PR DESCRIPTION
**Pull request by jiripetrlik**
Fixes #205

### CODE REVIEW

**Review by Maxusmusti — COMMENTED** [review]
hmm, when testing this myself, I am getting the following:
```
zsh: no matches found: *.html
```
Does this work locally for you, when you run `pdoc --html -o docs src/codeflare_sdk && pushd docs && rm -rf cluster job utils && mv codeflare_sdk/* . && rm -rf codeflare_sdk && popd && find docs -type f -name *.html -exec bash -c "echo '' >> {}" \;` in the codeflare-sdk dir?  If so maybe it's just a mac issue...

**Comment by Maxusmusti** [comment]
Aha, wrapping the `*.html` in quotes (`"*.html"`) solved the problems on my machine. So if that works for you as well, I'd recommend adding that.

**Comment by jiripetrlik** [comment]
@Maxusmusti 
Thank you for the review. It worked well on my Linux, but I've added quotes to be sure.

**Comment by Maxusmusti** [comment]
Awesome, looks like all it needs is a quick rebase and it's good for merging

**Comment by jiripetrlik** [comment]
@Maxusmusti 
Yes, thank you. It should be rebased now.

**Pull request merged**
