### PR TITLE
Added documentation for S3 compatible storage

### PR DESCRIPTION
**Pull request by Bobbins228**
# Issue link

[RHOAIENG-7805](https://issues.redhat.com/browse/RHOAIENG-7805)
# What changes have been made

Added documentation for S3 compatible storage options for the Torch Lightning demo and future demos that would make use of this documentation
# Verification steps

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [x] Testing is not required for this change

### CODE REVIEW

**Comment by VanillaSpoon** [comment]
/lgtm

Just a quick rebase and we're good to go!

**Review by VanillaSpoon — COMMENTED** [review]
/lgtm

Just a lil rebase and we're good to go!

**Review by KPostOffice — APPROVED** [review]

**Pull request merged**
