### PR TITLE
move busybox to quay.io

### PR DESCRIPTION
**Pull request by jbusche**
Closes #[324](https://github.com/project-codeflare/codeflare-sdk/issues/324)'

# What changes have been made
Swapping out the docker.io busybox to the quay.io one.

# Reason for the Change:
At least at IBM on our Fyre clusters, the docker.io pulls are getting a rate-limit error
```
Failed to pull image "busybox:1.28": rpc error: code = Unknown desc = reading manifest 1.28 in docker.io/library/busybox: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
But quay.io doesn't have a rate-limit issue, so we've moved the docker.io busybox over to quay.io and are using it in the tests and guided demos so that people don't see this docker pull issue in the future.

# Verification steps

## Checks
- [x] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [x] Manual tests
   - [ ] Testing is not required for this change

### CODE REVIEW

**Comment by jbusche** [comment]
Hey, unit tests looked good - thank you @tedhtchang with the help on getting poetry on my Mac working...
```
pytest -v tests/unit_test.py
=========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.9.16, pytest-7.4.0, pluggy-1.3.0 -- /root/.cache/pypoetry/virtualenvs/codeflare-sdk--BEgL2cU-py3.9/bin/python
cachedir: .pytest_cache
rootdir: /root/codeflare-sdk
configfile: pyproject.toml
plugins: mock-3.11.1
collected 58 items   
....
=========================================================================================== 58 passed in 10.60s ===========================================================================================

**Comment by jbusche** [comment]
Testing now in my cluster...

**Comment by jbusche** [comment]
Testing in my cluster looked good too - here's what I did
1.  Installed the normal way using @KPostOffice quickstart dsc method from [Quick-Start.md](https://github.com/KPostOffice/distributed-workloads/blob/issue149v1/Quick-Start.md)
2. The only two things I did differently was:
    2.1 Instead of using the Codeflare notebook image, I used the Jupyter Data Science image
    2.2 Instead of cloning the main branch of codeflare-sdk, I cloned my own branch and installed that version of codeflare with these steps:
```
git clone https://github.com/jbusche/codeflare-sdk.git -b jimb-pr324-2

cd codeflare-sdk/

pip list |grep codeflare
    codeflare-sdk                   0.10.1 
    codeflare-torchx                0.6.0.dev1

pip install -e .

pip list |grep codeflare
    codeflare-sdk                   0.0.0        /opt/app-root/src/JIM/codeflare-sdk
    codeflare-torchx                0.6.0.dev1
```
Now when I run the 0_basic_ray.ipynb or 2_basic_jobs.ipynb, instead of using the docker.io old version of busybox, it's using the quay.io newer version of busybox.

**Comment by jbusche** [comment]
job.status()
```
AppStatus:
  msg: !!python/object/apply:ray.dashboard.modules.job.common.JobStatus
  - SUCCEEDED
  num_restarts: -1
  roles:
  - replicas:
    - hostname: <NONE>
      id: 0
      role: ray
      state: !!python/object/apply:torchx.specs.api.AppState
      - 4
      structured_error_msg: <NONE>
    role: ray
  state: SUCCEEDED (4)
  structured_error_msg: <NONE>
  ui_url: null
```

**Review by tedhtchang — APPROVED** [review]
/LGTM

**Review by Fiona-Waters — COMMENTED** [review]
Tested changes on an OSD cluster - all works as expected using the quay image.
Screenshot from 2023-11-14 11-32-23
/lgtm

**Review by KPostOffice — APPROVED** [review]

**Pull request merged**
