### PR TITLE
change additionall to additional

### LINKED ISSUE #197: Typo "additionall" Instead of "additional" in the Demo Notebooks
There's a small typo in the Demo Notebooks.  Might be a good first issue for someone.

`grep -R additionall *`
```
demo-notebooks/guided-demos/3_basic_interactive.ipynb:    "#install additionall libraries that will be required for model training\n",
demo-notebooks/guided-demos/notebook-ex-outputs/3_basic_interactive.ipynb:    "#install additionall libraries that will be required for model training\n",
demo-notebooks/interactive/hf_interactive.ipynb:    "#install additionall libraries that will be required for this training\n",
```

### PR DESCRIPTION
**Pull request by vaibssingh**
This fixes the spelling issue with additional being spelled as additionall in ipynb files. Verified by running ```grep -R additionall *```

Fix #197

### CODE REVIEW

**Comment by jbusche** [comment]
Sure - It looks great!  I'm going to quick run it in a notebook, see how it looks, but should be good...

**Review by jbusche — APPROVED** [review]
LGTM, Thank you!

**Comment by MichaelClifford** [comment]
@vaibssingh can you make sure to run pre-commit locally, and then submit another commit. 

https://github.com/project-codeflare/codeflare-sdk#pre-commit

**Comment by vaibssingh** [comment]
@MichaelClifford Done!

**Comment by MichaelClifford** [comment]
@vaibssingh Hey Looks good, Can you please rebase? Then it will be good to merge.

**Comment by vaibssingh** [comment]
@MichaelClifford Done 👍🏽

**Comment by vaibssingh** [comment]
Hey @MichaelClifford , no I didn't do anything of that sort. I ```git pull origin main``` on my branch and resolved the conflicts and then pushed again. That may be the reason it is showing the commit history in my branch.

Do you need me to delete this branch and open a new PR?

**Comment by MichaelClifford** [comment]
You could probably still salvage it by reverting to an earlier state, pulling in the new upstream changes then adding your commit via a --force-push. 

This PR should really only have 1 commit "change additionall to addtional" on top of the most recent commits on the upstream main.

**Comment by vaibssingh** [comment]
Hey @MichaelClifford , thanks for your help. Have fixed the commit history 😄 
Let me know if there is something else that needs to be done here.

**Pull request merged**
